FROM maven:3.9.9-eclipse-temurin-17 AS builder

WORKDIR /build

COPY . .

RUN chmod +x mvnw

RUN ./mvnw -pl cli-input-adapter -am clean package -DskipTests

FROM eclipse-temurin:17-jre

WORKDIR /app

COPY --from=builder \
    /build/cli-input-adapter/target/*.jar \
    app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]